# Generated by Django 5.0.6 on 2024-06-03 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('Identifiant', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=300)),
                ('Numero', models.CharField(max_length=15)),
                ('date_naissance', models.DateField()),
                ('num_CNIB', models.CharField(max_length=20)),
                ('sexe', models.CharField(choices=[('SELECTIONNER', 'SELECTIONNER'), ('MASCULIN', 'MASCULIN'), ('FEMININ', 'FEMININ')], default='SELECTIONNER', max_length=12)),
                ('date_ajout', models.DateField(auto_now=True)),
                ('mot_de_passe', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Cours_Module',
            fields=[
                ('Id_module', models.AutoField(primary_key=True, serialize=False)),
                ('nom_module', models.CharField(max_length=250)),
                ('credit_module', models.IntegerField()),
                ('volume_horaire', models.CharField(max_length=10)),
                ('date_ajout', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['nom_module'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('Id_filiere', models.AutoField(primary_key=True, serialize=False)),
                ('nom_filiere', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['nom_filiere'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('matricule', models.AutoField(primary_key=True, serialize=False)),
                ('nom_etudiant', models.CharField(max_length=200)),
                ('prenom_etudiant', models.CharField(max_length=270)),
                ('email_etudiant', models.EmailField(max_length=254, unique=True)),
                ('telephone_etudiant', models.CharField(max_length=200)),
                ('sexe_etudiant', models.CharField(choices=[('Selectionner', 'Selectionner'), ('Masculin', 'Masculin'), ('Feminin', 'Feminin')], default='Selectionner', max_length=13)),
                ('Date_naiss_etudiant', models.DateField()),
                ('lieu_naiss_etudiant', models.CharField(max_length=200)),
                ('nationalite_etudiant', models.CharField(max_length=200)),
                ('niveau_etudiant', models.CharField(choices=[('LICENCE1', 'LICENCE1'), ('LICENCE2', 'LICENCE2'), ('LICENCE3', 'LICENCE3'), ('MASTER1', 'MASTER1'), ('MASTER2', 'MASTER2'), ('DOCTORAT', 'DOCTORAT')], default='Selectionner', max_length=200)),
                ('annee_academique_etudiant', models.CharField(max_length=100)),
                ('mdp_etudiant', models.CharField(blank=True, max_length=200)),
                ('date_ajout', models.DateField(auto_now=True)),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='Administration.filiere')),
            ],
            options={
                'ordering': ['nom_etudiant'],
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('Id_note', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note1', models.FloatField()),
                ('Note2', models.FloatField()),
                ('moyenne', models.FloatField(default=0.0, editable=False)),
                ('etudiant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Administration.etudiant')),
                ('matiere_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Administration.cours_module')),
            ],
        ),
    ]
