# Generated by Django 5.0.6 on 2024-10-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours_module',
            name='unite_enseignement',
            field=models.CharField(choices=[('FONDAMENTALE', "Unité d'enseignement fondamentale"), ('TRANSVERSALE', "Unité d'enseignement transversale")], default='FONDAMENTALE', max_length=50),
        ),
    ]
