# Generated by Django 5.0.6 on 2024-10-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0002_cours_module_unite_enseignement'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='mention',
            field=models.CharField(choices=[('GENIE ELECTRIQUE', 'GE'), ('GENIE MECANIQUE', 'GM'), ('GENIE LOGICIEL', 'GL'), ('MANAGEMENT', 'MGMT')], default='GENIE ELECTRIQUE', max_length=50),
        ),
    ]
