# Generated by Django 5.0.6 on 2024-10-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0002_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='mdp_etudiant',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='sexe_etudiant',
            field=models.CharField(choices=[('Selectionner', 'Selectionner'), ('Masculin', 'Masculin'), ('Feminin', 'Feminin')], default='Masculin', max_length=13),
        ),
    ]
