# Generated by Django 5.0.6 on 2024-06-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0002_alter_notes_matiere_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='Id_note',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
