# Generated by Django 5.0.6 on 2024-07-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0003_alter_administration_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='administration',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='administration',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='administration',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='administration',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='administration',
            name='username',
        ),
        migrations.AlterField(
            model_name='administration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='administration',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
