# Generated by Django 5.0.6 on 2024-10-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0003_filiere_mention'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours_module',
            name='semestre',
            field=models.CharField(choices=[('SEMESTRE 1', 'S1'), ('SEMESTRE 2', 'S2')], default='SEMESTRE 1', max_length=50),
        ),
    ]
