# Generated by Django 5.0.6 on 2024-10-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0003_alter_etudiant_mdp_etudiant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='type_bac',
            field=models.CharField(choices=[('BACCALAUREAT SERIE A1', 'BACCALAUREAT SERIE A1'), ('BACCALAUREAT SERIE A2', 'BACCALAUREAT SERIE A2'), ('BACCALAUREAT SERIE C', 'BACCALAUREAT SERIE C'), ('BACCALAUREAT SERIE D', 'BACCALAUREAT SERIE D'), ('BACCALAUREAT SERIE E', 'BACCALAUREAT SERIE E'), ('BACCALAUREAT SERIE F4', 'BACCALAUREAT SERIE F4'), ('BACCALAUREAT SERIE F2', 'BACCALAUREAT SERIE F2')], default='BACCALAUREAT SERIE D', max_length=25),
        ),
    ]
