# Generated by Django 4.0 on 2024-07-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Administration', '0004_alter_administration_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boursier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_bourse', models.CharField(choices=[('non_boursier', 'Non Boursier'), ('boursier_etat', "Boursier de l'Etat"), ('boursier_particulier_50', 'Boursier Particulier 50%'), ('boursier_particulier_75', 'Boursier Particulier 75%')], default='non_boursier', max_length=50)),
                ('reduction', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='boursier',
        ),
        migrations.AlterField(
            model_name='administration',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='administration_user_set', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='administration',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='administration_user_set', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='bourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Administration.boursier'),
        ),
    ]
