# Generated by Django 5.0.6 on 2024-10-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0004_etudiant_type_bac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursfichier',
            old_name='Id_fichier',
            new_name='id_fichier',
        ),
    ]
