# Generated by Django 5.0.6 on 2024-10-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0005_rename_id_fichier_coursfichier_id_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='scolarite',
            name='annee_academique',
            field=models.CharField(default='2023/2024', max_length=20),
        ),
    ]
