# Generated by Django 4.0 on 2024-07-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0005_boursier_remove_etudiant_boursier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='montant_restant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='montant_total_verse',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
