# Generated by Django 4.0 on 2024-07-26 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0006_etudiant_montant_restant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='montant_restant',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='Administration.filiere'),
        ),
        migrations.CreateModel(
            name='ListEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_scolarite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.scolarite')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.etudiant')),
            ],
            options={
                'verbose_name': 'ListEtudiant',
                'verbose_name_plural': 'ListEtudiants',
            },
        ),
    ]
