# Generated by Django 5.0.6 on 2024-10-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0006_scolarite_annee_academique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
