# Generated by Django 5.0.6 on 2024-06-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0007_alter_administration_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administration',
            options={'ordering': ['-date_ajout'], 'verbose_name': 'Administration', 'verbose_name_plural': 'Administrations'},
        ),
        migrations.AlterModelOptions(
            name='cours_module',
            options={'ordering': ['nom_module'], 'verbose_name': 'Cours_Module', 'verbose_name_plural': 'Cours_Modules'},
        ),
        migrations.AlterModelOptions(
            name='enseignement',
            options={'ordering': ['date_ajout'], 'verbose_name': 'Enseignement', 'verbose_name_plural': 'Enseignements'},
        ),
        migrations.AlterModelOptions(
            name='etudiant',
            options={'ordering': ['nom_etudiant'], 'verbose_name': 'Etudiant', 'verbose_name_plural': 'Etudiants'},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['matiere_module'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterModelOptions(
            name='professeurs',
            options={'ordering': ['-date_ajout'], 'verbose_name': 'professeur', 'verbose_name_plural': 'professeurs'},
        ),
        migrations.AddField(
            model_name='enseignement',
            name='date_ajout',
            field=models.DateField(auto_now=True),
        ),
    ]
