# Generated by Django 4.0 on 2024-07-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0007_remove_etudiant_montant_restant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='montant_total_verse',
        ),
    ]
