# Generated by Django 5.0.6 on 2024-11-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0008_alter_etudiant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursfichier',
            name='type_fichier',
            field=models.CharField(choices=[('Cours', 'Cours'), ('TD', 'TD'), ('Devoir ', 'Devoir ')], default='Selectionner', max_length=200),
        ),
    ]
