# Generated by Django 5.0.6 on 2024-11-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0009_alter_coursfichier_type_fichier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploaded_at',
        ),
    ]
