# Generated by Django 4.0 on 2024-07-26 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0009_rename__scolarite_listetudiant_scolarite'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='montant_total_verse',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='Administration.filiere'),
        ),
        migrations.DeleteModel(
            name='ListEtudiant',
        ),
    ]
