# Generated by Django 4.0 on 2024-07-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0010_etudiant_montant_total_verse_alter_etudiant_filiere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='montant_restant',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=10),
            preserve_default=False,
        ),
    ]
