# Generated by Django 5.0.6 on 2024-11-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0010_remove_uploadedfile_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de téléchargement'),
        ),
    ]
