# Generated by Django 5.0.6 on 2024-11-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0011_uploadedfile_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('terminee', 'Terminée'), ('en_retard', 'En retard')], default='en_attente', max_length=10, verbose_name='Statut')),
            ],
        ),
    ]
