# Generated by Django 5.0.6 on 2024-11-17 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0011_uploadedfile_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursfichier',
            name='type_fichier',
            field=models.CharField(choices=[('Cours', 'Cours'), ('TD', 'TD'), ('Devoir 1', 'Devoir 1'), ('Devoir 2', 'Devoir 2'), ('Devoir Session ', 'Devoir Session')], default='Selectionner', max_length=200),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='type_bac',
            field=models.CharField(choices=[('BACCALAUREAT SERIE A1', 'BACCALAUREAT SERIE A1'), ('BACCALAUREAT SERIE A4', 'BACCALAUREAT SERIE A4'), ('BACCALAUREAT SERIE C', 'BACCALAUREAT SERIE C'), ('BACCALAUREAT SERIE D', 'BACCALAUREAT SERIE D'), ('BACCALAUREAT SERIE E', 'BACCALAUREAT SERIE E'), ('BACCALAUREAT SERIE F4', 'BACCALAUREAT SERIE F4'), ('BACCALAUREAT SERIE F2', 'BACCALAUREAT SERIE F2')], default='BACCALAUREAT SERIE D', max_length=25),
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('terminee', 'Terminée'), ('en_retard', 'En retard')], default='en_attente', max_length=10, verbose_name='Statut')),
                ('professeur', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='Administration.professeurs')),
            ],
        ),
    ]
