# Generated by Django 4.0 on 2024-07-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0011_etudiant_montant_restant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='annee_academique_etudiant',
            field=models.CharField(choices=[('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026'), ('2026/2027', '2026/2027'), ('2027/2028', '2027/2028'), ('2028/2029', '2028/2029')], default='Selectionner', max_length=100),
        ),
    ]
