# Generated by Django 5.0.6 on 2024-11-17 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0012_tache'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='professeur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='Administration.professeurs'),
        ),
    ]
