# Generated by Django 4.0 on 2024-07-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0012_alter_etudiant_annee_academique_etudiant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='montant_restant',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='Montant_restant',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scolarite',
            name='montant_total_verse',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='montant_total_verse',
            field=models.FloatField(default=0.0),
        ),
    ]
