# Generated by Django 5.0.6 on 2024-11-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0012_alter_coursfichier_type_fichier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursfichier',
            name='type_fichier',
            field=models.CharField(choices=[('Cours', 'Cours'), ('TD', 'TD'), ('Devoir', 'Devoir '), ('Devoir Session ', 'Devoir Session')], default='Selectionner', max_length=200),
        ),
    ]
