# Generated by Django 4.2.2 on 2024-06-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0013_utilisateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
