# Generated by Django 4.0 on 2024-07-28 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0013_remove_etudiant_montant_restant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursFichier',
            fields=[
                ('Id_fichier', models.AutoField(primary_key=True, serialize=False)),
                ('nom_fichier', models.CharField(max_length=250)),
                ('fichier', models.FileField(upload_to='cours_pdf/')),
                ('date_ajout', models.DateField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='Administration.cours_module')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_fichiers', to='Administration.professeurs')),
            ],
            options={
                'verbose_name': 'Cours Fichier',
                'verbose_name_plural': 'Cours Fichiers',
                'ordering': ['date_ajout'],
            },
        ),
    ]
