# Generated by Django 5.0.6 on 2024-11-19 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0013_alter_coursfichier_type_fichier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesseurFiliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.filiere')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.professeurs')),
            ],
            options={
                'unique_together': {('professeur', 'filiere')},
            },
        ),
    ]
