# Generated by Django 5.0.6 on 2024-11-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0014_professeurfiliere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='message',
            field=models.TextField(max_length=1000000),
        ),
    ]
