# Generated by Django 4.2.2 on 2024-06-06 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0014_delete_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours_module',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='Administration.filiere'),
            preserve_default=False,
        ),
    ]
