# Generated by Django 5.0.6 on 2024-11-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0015_alter_infos_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='nom_personne_prevenir',
            field=models.CharField(blank=True, default='Non specifie', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='numero_personne_prevenir',
            field=models.CharField(blank=True, default='0000000000', max_length=15, null=True),
        ),
    ]
