# Generated by Django 4.0 on 2024-07-28 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0015_alter_coursfichier_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursfichier',
            name='annee_academique_cour',
            field=models.CharField(choices=[('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026'), ('2026/2027', '2026/2027'), ('2027/2028', '2027/2028'), ('2028/2029', '2028/2029')], default='Selectionner', max_length=100),
        ),
        migrations.AddField(
            model_name='coursfichier',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichier', to='Administration.etudiant'),
        ),
    ]
