# Generated by Django 5.0.6 on 2024-11-17 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0016_alter_tache_options_alter_tache_date_echeance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tache',
            options={},
        ),
        migrations.RemoveField(
            model_name='tache',
            name='date_echeance',
        ),
    ]
