# Generated by Django 4.2.2 on 2024-06-06 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0016_alter_cours_module_filiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours_module',
            name='filiere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='Administration.filiere'),
        ),
    ]
