# Generated by Django 5.0.6 on 2024-12-03 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0017_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='chef_de_classe',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AvancementCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_horaire_total', models.IntegerField(help_text='Volume horaire total du cours')),
                ('volume_horaire_realise', models.IntegerField(help_text='Volume horaire déjà réalisé')),
                ('pourcentage_avancement', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cours_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avancements', to='Administration.cours_module')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avancements', to='Administration.etudiant')),
            ],
        ),
    ]
