# Generated by Django 4.0 on 2024-07-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0017_coursfichier_niveau_etudiant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursfichier',
            old_name='niveau_etudiant',
            new_name='niveauEtudiant',
        ),
    ]
