# Generated by Django 5.0.6 on 2024-06-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0017_alter_cours_module_filiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scolarite',
            name='total',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
