# Generated by Django 5.0.6 on 2024-12-06 23:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0018_etudiant_chef_de_classe_avancementcours'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancementcours',
            name='date_op',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
