# Generated by Django 4.0 on 2024-07-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0018_rename_niveau_etudiant_coursfichier_niveauetudiant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursfichier',
            name='niveauEtudiant',
        ),
        migrations.AddField(
            model_name='coursfichier',
            name='niveau',
            field=models.CharField(choices=[('LICENCE1', 'LICENCE1'), ('LICENCE2', 'LICENCE2'), ('LICENCE3', 'LICENCE3'), ('MASTER1', 'MASTER1'), ('MASTER2', 'MASTER2'), ('DOCTORAT', 'DOCTORAT')], default='Selectionner', max_length=200),
        ),
    ]
