# Generated by Django 5.0.6 on 2024-06-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0018_alter_scolarite_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='boursier',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
