# Generated by Django 5.0.6 on 2024-12-07 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0019_avancementcours_date_op'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avancementcours',
            name='date_op',
        ),
    ]
