# Generated by Django 4.0 on 2024-07-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0019_remove_coursfichier_niveauetudiant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursfichier',
            name='fichier',
            field=models.FileField(upload_to='media/cours/'),
        ),
    ]
