# Generated by Django 5.0.6 on 2024-06-23 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0019_etudiant_boursier'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours_module',
            name='professeur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='Administration.professeurs'),
        ),
    ]
