# Generated by Django 4.0 on 2024-07-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0020_alter_coursfichier_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursfichier',
            name='fichier',
            field=models.FileField(upload_to='cours/'),
        ),
    ]
