# Generated by Django 5.0.6 on 2024-12-07 01:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0020_remove_avancementcours_date_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancementcours',
            name='date_op',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
