# Generated by Django 4.0 on 2024-07-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0021_alter_coursfichier_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeurs',
            name='niveau_prof',
            field=models.CharField(choices=[('Selectionner', 'Selectionner'), ('Docteur', 'Docteur'), ('Professeur', 'Professeur'), ('Ing', 'Ingénieur'), ('Lamda', 'Lamda'), ('Vacataire', 'Vacataire')], default='Selectionner', max_length=20),
        ),
    ]
