# Generated by Django 5.0.6 on 2024-12-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0021_avancementcours_date_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancementcours',
            name='volume_horaire_restant',
            field=models.IntegerField(default=0),
        ),
    ]
