# Generated by Django 4.0 on 2024-07-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0022_alter_professeurs_niveau_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursfichier',
            name='type_fichier',
            field=models.CharField(choices=[('Cours', 'Cours'), ('TD', 'TD'), ('Devoir 1', 'Devoir 1'), ('Devoir 2', 'Devoir 2'), ('Devoir Session ', 'Devoir Session')], default='Selectionner', max_length=200),
        ),
    ]
