# Generated by Django 5.0.6 on 2024-12-29 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0022_avancementcours_volume_horaire_restant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='Id_note',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='Note1',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='Note2',
        ),
        migrations.AddField(
            model_name='notes',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='notes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='cours_module',
            name='semestre',
            field=models.CharField(choices=[('SEMESTRE 1', 'S1'), ('SEMESTRE 2', 'S2'), ('SEMESTRE 3', 'S3'), ('SEMESTRE 4', 'S4'), ('SEMESTRE 5', 'S5'), ('SEMESTRE 6', 'S6')], default='SEMESTRE 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='notes',
            name='etudiant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Administration.etudiant'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='matiere_module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Administration.cours_module'),
        ),
        migrations.AddIndex(
            model_name='notes',
            index=models.Index(fields=['etudiant'], name='Administrat_etudian_746292_idx'),
        ),
        migrations.AddIndex(
            model_name='notes',
            index=models.Index(fields=['matiere_module'], name='Administrat_matiere_84b52c_idx'),
        ),
    ]
