# Generated by Django 4.0 on 2024-07-29 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0023_coursfichier_type_fichier'),
    ]

    operations = [
        migrations.CreateModel(
            name='prix_scolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scolarity', to='Administration.etudiant')),
                ('scolarite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_prices', to='Administration.scolarite')),
            ],
        ),
    ]
