# Generated by Django 5.0.6 on 2024-12-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0023_remove_notes_id_note_remove_notes_note1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
