# Generated by Django 5.0.6 on 2024-12-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0024_alter_notes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
