# Generated by Django 4.0 on 2024-07-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0024_prix_scolarite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prix_scolarite',
            name='id',
        ),
        migrations.AddField(
            model_name='prix_scolarite',
            name='id_prix',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
