# Generated by Django 5.0.6 on 2025-01-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0025_notes_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scolarite',
            name='tranche_1',
        ),
        migrations.RemoveField(
            model_name='scolarite',
            name='tranche_2',
        ),
        migrations.RemoveField(
            model_name='scolarite',
            name='tranche_3',
        ),
        migrations.AddField(
            model_name='scolarite',
            name='tranches',
            field=models.JSONField(default=list),
        ),
    ]
