# Generated by Django 5.1.6 on 2025-02-17 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0026_remove_scolarite_tranche_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancementcours',
            name='heure_debut',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Heure de début du cours'),
        ),
        migrations.AddField(
            model_name='avancementcours',
            name='heure_fin',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Heure de fin du cours'),
        ),
        migrations.AddField(
            model_name='avancementcours',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
