# Generated by Django 4.0 on 2024-07-29 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0027_rename_student_prix_scolarite_etudiant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='Montant_restant',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='montant_total_verse',
        ),
        migrations.RemoveField(
            model_name='prix_scolarite',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='prix_scolarite',
            name='scolarite',
        ),
        migrations.AddField(
            model_name='prix_scolarite',
            name='Montant_restant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_prices', to='Administration.scolarite'),
        ),
        migrations.AddField(
            model_name='prix_scolarite',
            name='annee_academique_etudiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_level', to='Administration.etudiant'),
        ),
        migrations.AddField(
            model_name='prix_scolarite',
            name='matricule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_matricule', to='Administration.etudiant'),
        ),
        migrations.AddField(
            model_name='prix_scolarite',
            name='montant_total_verse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_year', to='Administration.scolarite'),
        ),
        migrations.AddField(
            model_name='prix_scolarite',
            name='niveau_etudiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_filier', to='Administration.etudiant'),
        ),
        migrations.AddField(
            model_name='prix_scolarite',
            name='nom_etudiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_name', to='Administration.etudiant'),
        ),
        migrations.AddField(
            model_name='prix_scolarite',
            name='nom_filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_firsname', to='Administration.etudiant'),
        ),
        migrations.AddField(
            model_name='prix_scolarite',
            name='total',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_due', to='Administration.scolarite'),
        ),
        migrations.AddField(
            model_name='prix_scolarite',
            name='tranche_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment1', to='Administration.scolarite'),
        ),
        migrations.AddField(
            model_name='prix_scolarite',
            name='tranche_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment2', to='Administration.scolarite'),
        ),
        migrations.AddField(
            model_name='prix_scolarite',
            name='tranche_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment3', to='Administration.scolarite'),
        ),
    ]
