# Generated by Django 5.1.6 on 2025-02-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0027_avancementcours_heure_debut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='avancement_images/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='avancementcours',
            name='images',
        ),
        migrations.AddField(
            model_name='avancementcours',
            name='images',
            field=models.ManyToManyField(to='Administration.image'),
        ),
    ]
