# Generated by Django 4.0 on 2024-07-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0028_remove_etudiant_montant_restant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='Montant_restant',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='montant_total_verse',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='prix_scolarite',
        ),
    ]
