# Generated by Django 5.1.6 on 2025-02-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0028_image_remove_avancementcours_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avancementcours',
            name='images',
        ),
        migrations.AddField(
            model_name='avancementcours',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avancement_images/'),
        ),
    ]
