# Generated by Django 5.0.7 on 2024-08-05 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0013_uploadedfile'),
        ('Administration', '0029_etudiant_montant_restant_and_more'),
    ]

    operations = [
    ]
