# Generated by Django 5.1.6 on 2025-02-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0029_remove_avancementcours_images_avancementcours_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancementcours',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='avancement_images/'),
        ),
    ]
