# Generated by Django 5.0.7 on 2024-08-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0030_merge_20240805_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='mdp_etudiant',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='mot_de_passe_haché',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploaded_files/*'),
        ),
    ]
