# Generated by Django 5.1.6 on 2025-02-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0030_avancementcours_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancementcours',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='avancement_images/'),
        ),
    ]
