# Generated by Django 5.1.6 on 2025-03-10 18:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0031_avancementcours_image3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('present', models.BooleanField(default=False)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.cours_module')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.etudiant')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.enseignement')),
            ],
            options={
                'unique_together': {('etudiant', 'cours', 'date')},
            },
        ),
    ]
