# Generated by Django 5.0.7 on 2024-08-08 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0031_remove_etudiant_mdp_etudiant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='Montant_restant',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='montant_total_verse',
        ),
    ]
