# Generated by Django 5.0.7 on 2024-08-09 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0032_remove_etudiant_montant_restant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='mot_de_passe_haché',
            new_name='mot_de_passe_hache',
        ),
    ]
