# Generated by Django 5.1.6 on 2025-03-11 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0032_appel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appel',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appel', to='Administration.etudiant'),
        ),
    ]
