# Generated by Django 5.1.6 on 2025-03-19 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0033_alter_appel_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeurs',
            name='CNIB',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='professeurs',
            name='CV',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='professeurs',
            name='Contrat_paiement',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='professeurs',
            name='attestion_cames',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='professeurs',
            name='dernier_diplome',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='professeurs',
            name='numero_autorisation_enseignement',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='professeurs',
            name='ordre_mission',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='appel',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.professeurs'),
        ),
    ]
