# Generated by Django 5.0.7 on 2024-08-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0033_rename_mot_de_passe_haché_etudiant_mot_de_passe_hache'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='mdp_etudiant',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='mot_de_passe_hache',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
