# Generated by Django 5.0.6 on 2024-08-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0034_etudiant_mdp_etudiant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='mot_de_passe_hache',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='montant_restant',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='montant_total_verse',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='mdp_etudiant',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploaded_files/'),
        ),
    ]
