# Generated by Django 5.1.6 on 2025-04-14 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0034_professeurs_cnib_professeurs_cv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.filiere')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.cours_module')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.professeurs')),
            ],
        ),
    ]
