# Generated by Django 5.0.6 on 2024-08-21 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0035_remove_etudiant_mot_de_passe_hache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours_module',
            name='niveau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='niveau', to='Administration.etudiant'),
        ),
    ]
