# Generated by Django 5.0.6 on 2024-08-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0036_cours_module_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours_module',
            name='niveau',
            field=models.CharField(choices=[('LICENCE1', 'LICENCE1'), ('LICENCE2', 'LICENCE2'), ('LICENCE3', 'LICENCE3'), ('MASTER1', 'MASTER1'), ('MASTER2', 'MASTER2'), ('DOCTORAT', 'DOCTORAT')], default='Selectionner', max_length=200),
        ),
    ]
