# Generated by Django 5.0.7 on 2024-09-03 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0037_alter_cours_module_niveau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='montant_restant',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='montant_total_verse',
        ),
    ]
