# Generated by Django 5.0.7 on 2024-09-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0038_remove_etudiant_montant_restant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
