# Generated by Django 5.0.7 on 2024-09-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0040_alter_etudiant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
