# Generated by Django 5.0.7 on 2024-09-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0041_alter_etudiant_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='infos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=100000)),
                ('contenu', models.FileField(upload_to='infos')),
                ('date_creation', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'info',
                'verbose_name_plural': 'infos',
                'ordering': ['date_creation'],
            },
        ),
    ]
