# Generated by Django 5.0.7 on 2024-09-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0042_infos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infos',
            old_name='id',
            new_name='id_infos',
        ),
    ]
