# Generated by Django 5.0.7 on 2024-09-06 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0043_rename_id_infos_id_infos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infos',
            old_name='nom',
            new_name='titre',
        ),
    ]
