# Generated by Django 5.0.6 on 2024-09-06 13:52

import Administration.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0045_alter_infos_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='mdp_etudiant',
            field=models.CharField(blank=True, max_length=9, validators=[Administration.models.validate_password_special_char, django.core.validators.MinLengthValidator(8)]),
        ),
    ]
