# Generated by Django 5.1.1 on 2024-09-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0046_alter_etudiant_mdp_etudiant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'ordering': ['date_ajout'], 'verbose_name': 'file', 'verbose_name_plural': 'files'},
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='scolarite',
            name='frais_inscription',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='date_ajout',
            field=models.DateField(auto_now=True),
        ),
    ]
