# Generated by Django 5.1.1 on 2024-09-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0046_alter_etudiant_mdp_etudiant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
