# Generated by Django 5.1.1 on 2024-09-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0047_remove_uploadedfile_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scolarite',
            name='frais_inscription',
            field=models.FloatField(default=1),
        ),
    ]
