# Generated by Django 5.0.6 on 2024-06-03 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='matiere_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='Administration.cours_module'),
        ),
    ]
