# Generated by Django 5.0.6 on 2024-06-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0003_alter_notes_id_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='proffesseurs',
            fields=[
                ('Id_prof', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prof', models.CharField(max_length=150)),
                ('prenom_prof', models.CharField(max_length=300)),
                ('email_prof', models.EmailField(max_length=400)),
                ('niveau_prof', models.CharField(choices=[('Selectionner', 'Selectionner'), ('Docteur', 'Docteur'), ('Professeur', 'Professeur'), ('Ingénieur', 'Ingénieur'), ('Lamda', 'Lamda'), ('Vacataire', 'Vacataire')], default='Selectionner', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notes',
            name='Note1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='notes',
            name='Note2',
            field=models.FloatField(default=0),
        ),
    ]
