# Generated by Django 5.0.6 on 2024-06-04 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0004_proffesseurs_alter_etudiant_matricule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_enseigner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursenseigner', to='Administration.cours_module')),
            ],
        ),
        migrations.CreateModel(
            name='professeurs',
            fields=[
                ('Id_prof', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prof', models.CharField(max_length=150)),
                ('prenom_prof', models.CharField(max_length=300)),
                ('email_prof', models.EmailField(max_length=400)),
                ('niveau_prof', models.CharField(choices=[('Selectionner', 'Selectionner'), ('Docteur', 'Docteur'), ('Professeur', 'Professeur'), ('C', 'Ingénieur'), ('Lamda', 'Lamda'), ('Vacataire', 'Vacataire')], default='Selectionner', max_length=20)),
                ('mdp_prof', models.CharField(blank=True, max_length=600)),
                ('numero_prof', models.CharField(max_length=20)),
                ('date_ajout', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.DeleteModel(
            name='proffesseurs',
        ),
        migrations.AddField(
            model_name='enseignement',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof', to='Administration.professeurs'),
        ),
    ]
