# Generated by Django 5.0.6 on 2024-06-04 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0005_enseignement_professeurs_delete_proffesseurs_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='administration',
            table='Administration',
        ),
    ]
