# Generated by Django 5.0.6 on 2024-06-04 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0006_alter_administration_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='administration',
            table=None,
        ),
    ]
