# Generated by Django 5.0.6 on 2024-06-04 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0008_alter_administration_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solarite',
            fields=[
                ('Id_scolarite', models.AutoField(primary_key=True, serialize=False)),
                ('tranche_1', models.FloatField(default=0)),
                ('tranche_2', models.FloatField(default=0)),
                ('tranche_3', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('Montant_restant', models.FloatField(default=0.0, editable=False)),
                ('etudiant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scolarite', to='Administration.etudiant')),
            ],
        ),
    ]
