# Generated by Django 5.0.6 on 2024-06-04 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0009_solarite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solarite',
            new_name='Scolarite',
        ),
    ]
