# Generated by Django 5.0.6 on 2024-06-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0010_rename_solarite_scolarite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scolarite',
            options={'ordering': ['-date_payement'], 'verbose_name': 'Scolarite', 'verbose_name_plural': 'Scolarite'},
        ),
        migrations.AddField(
            model_name='scolarite',
            name='date_payement',
            field=models.DateField(auto_now=True),
        ),
    ]
