# Generated by Django 4.2.2 on 2024-06-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0011_alter_scolarite_options_scolarite_date_payement'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='password_updated',
            field=models.BooleanField(default=False),
        ),
    ]
